-- v0.1.274 additive schema upgrade for PostgreSQL (hotfix shipped as v0.1.275).
--
-- Background: the 0252-compat PostgreSQL baseline was frozen at the cutover.
-- v0.1.274 added, for SQLite backends inside app.init_db():
--   * service_report_workers.origin_address / trip_type  (日报「员工出发地 + 行程类型」)
--   * service_report_mileage_evidence table + report index (里程佐证)
-- PostgreSQL mode never runs init_db DDL (schema changes require the migration
-- tool), so production PG missed the objects and every report page that loads
-- existing workers (编辑 / 复制 / 查看 / 保存) failed with a missing-column 500.
--
-- This file mirrors those EXACT app.py definitions, is additive-only and fully
-- idempotent, so it is safe to run on every deploy while the application is up:
--   * ADD COLUMN IF NOT EXISTS is metadata-only on PostgreSQL 11+ (no rewrite).
--   * The new table starts empty, so its FK validates instantly.
--   * invoice_sqlite_columns bookkeeping is upserted with ON CONFLICT DO
--     NOTHING so PRAGMA table_info() translations see the new columns.
-- The invoice_schema_version marker intentionally stays '0252-compat-v2': the
-- additive objects do not change any reviewed 0252 behaviour, and bumping the
-- marker would make the running verifier refuse to start before the upgrade
-- has been applied (deployment dead-lock). The upgrade runner verifies actual
-- object presence instead of the marker.
--
-- Run inside a single transaction (psql --single-transaction / -1) with
-- ON_ERROR_STOP by scripts/upgrade_postgresql.py, as the migration (owner) role.

SET lock_timeout = '15s';
SET statement_timeout = '60s';

ALTER TABLE service_report_workers
    ADD COLUMN IF NOT EXISTS origin_address text NOT NULL DEFAULT '';
ALTER TABLE service_report_workers
    ADD COLUMN IF NOT EXISTS trip_type text NOT NULL DEFAULT 'round_trip';

CREATE TABLE IF NOT EXISTS service_report_mileage_evidence (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    report_id bigint NOT NULL,
    worker_user_id bigint NOT NULL,
    route_fingerprint text NOT NULL,
    origin_address text NOT NULL DEFAULT '',
    destination_address text NOT NULL DEFAULT '',
    trip_type text NOT NULL DEFAULT 'round_trip',
    distance_meters double precision,
    duration_seconds bigint,
    one_way_miles double precision,
    reported_miles double precision,
    attachment_id bigint,
    status text NOT NULL DEFAULT 'success',
    generated_by bigint,
    generated_at text NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (report_id, worker_user_id),
    FOREIGN KEY (report_id) REFERENCES service_reports(id) ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE INDEX IF NOT EXISTS idx_sr_mileage_evidence_report
    ON service_report_mileage_evidence(report_id);

-- PRAGMA table_info() on PostgreSQL reads this bookkeeping table; mirror the
-- SQLite manifest entries the reviewed migrator would have written.
INSERT INTO invoice_sqlite_columns (table_name, cid, name, type, "notnull", dflt_value, pk) VALUES
    ('service_report_workers', 8, 'origin_address', 'TEXT', 1, '''''', 0),
    ('service_report_workers', 9, 'trip_type', 'TEXT', 1, '''round_trip''', 0),
    ('service_report_mileage_evidence', 0, 'id', 'INTEGER', 0, NULL, 1),
    ('service_report_mileage_evidence', 1, 'report_id', 'INTEGER', 1, NULL, 0),
    ('service_report_mileage_evidence', 2, 'worker_user_id', 'INTEGER', 1, NULL, 0),
    ('service_report_mileage_evidence', 3, 'route_fingerprint', 'TEXT', 1, NULL, 0),
    ('service_report_mileage_evidence', 4, 'origin_address', 'TEXT', 1, '''''', 0),
    ('service_report_mileage_evidence', 5, 'destination_address', 'TEXT', 1, '''''', 0),
    ('service_report_mileage_evidence', 6, 'trip_type', 'TEXT', 1, '''round_trip''', 0),
    ('service_report_mileage_evidence', 7, 'distance_meters', 'REAL', 0, NULL, 0),
    ('service_report_mileage_evidence', 8, 'duration_seconds', 'INTEGER', 0, NULL, 0),
    ('service_report_mileage_evidence', 9, 'one_way_miles', 'REAL', 0, NULL, 0),
    ('service_report_mileage_evidence', 10, 'reported_miles', 'REAL', 0, NULL, 0),
    ('service_report_mileage_evidence', 11, 'attachment_id', 'INTEGER', 0, NULL, 0),
    ('service_report_mileage_evidence', 12, 'status', 'TEXT', 1, '''success''', 0),
    ('service_report_mileage_evidence', 13, 'generated_by', 'INTEGER', 0, NULL, 0),
    ('service_report_mileage_evidence', 14, 'generated_at', 'TEXT', 1, NULL, 0)
ON CONFLICT (table_name, cid) DO NOTHING;
