-- v0.1.285 Employee payment center, treasury, advances and asset management.
-- PostgreSQL is the sole production schema. All changes are additive and preserve
-- the existing payroll, expense, profitability and audit tables.

CREATE TABLE IF NOT EXISTS bank_accounts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_name text NOT NULL UNIQUE,
    bank_name text NOT NULL DEFAULT '',
    account_type text NOT NULL DEFAULT 'checking',
    currency text NOT NULL DEFAULT 'USD',
    last_four text NOT NULL DEFAULT '',
    opening_balance numeric(14,2) NOT NULL DEFAULT 0,
    is_active integer NOT NULL DEFAULT 1 CHECK (is_active IN (0,1)),
    external_account_id text,
    sync_source text NOT NULL DEFAULT 'manual',
    sync_status text NOT NULL DEFAULT 'local',
    last_synced_at text,
    created_by bigint REFERENCES users(id),
    created_at text NOT NULL,
    updated_at text NOT NULL
);

CREATE TABLE IF NOT EXISTS employee_salary_agreements (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id bigint NOT NULL REFERENCES users(id),
    amount numeric(14,2) NOT NULL CHECK (amount >= 0),
    currency text NOT NULL DEFAULT 'USD',
    effective_from text NOT NULL,
    effective_to text,
    replaces_system_payroll integer NOT NULL DEFAULT 1 CHECK (replaces_system_payroll IN (0,1)),
    notes text NOT NULL DEFAULT '',
    is_active integer NOT NULL DEFAULT 1 CHECK (is_active IN (0,1)),
    created_by bigint REFERENCES users(id),
    created_at text NOT NULL,
    updated_at text NOT NULL,
    CHECK (effective_to IS NULL OR effective_to >= effective_from)
);
CREATE INDEX IF NOT EXISTS idx_salary_agreements_employee_dates
    ON employee_salary_agreements(employee_id,effective_from,effective_to);

CREATE TABLE IF NOT EXISTS employee_advances (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    advance_number text NOT NULL UNIQUE,
    employee_id bigint NOT NULL REFERENCES users(id),
    principal_amount numeric(14,2) NOT NULL CHECK (principal_amount > 0),
    currency text NOT NULL DEFAULT 'USD',
    advance_date text NOT NULL,
    bank_account_id bigint REFERENCES bank_accounts(id),
    purpose text NOT NULL DEFAULT '',
    attachment_name text NOT NULL DEFAULT '',
    attachment_stored_filename text NOT NULL DEFAULT '',
    status text NOT NULL DEFAULT 'open' CHECK (status IN ('open','settled','cancelled')),
    external_transaction_id text,
    sync_source text NOT NULL DEFAULT 'manual',
    sync_status text NOT NULL DEFAULT 'local',
    created_by bigint REFERENCES users(id),
    created_at text NOT NULL,
    updated_at text NOT NULL
);
ALTER TABLE employee_advances
    ADD COLUMN IF NOT EXISTS attachment_stored_filename text NOT NULL DEFAULT '';
CREATE INDEX IF NOT EXISTS idx_employee_advances_employee ON employee_advances(employee_id,status);

CREATE TABLE IF NOT EXISTS employee_payment_orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_number text NOT NULL UNIQUE,
    employee_id bigint NOT NULL REFERENCES users(id),
    payment_type text NOT NULL CHECK (payment_type IN ('system_payroll','offline_salary','expense','bonus','allowance','other')),
    status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','pending_review','approved','pending_payment','paid','reconciled','rejected','cancelled','payment_failed')),
    currency text NOT NULL DEFAULT 'USD',
    gross_amount numeric(14,2) NOT NULL CHECK (gross_amount >= 0),
    advance_offset numeric(14,2) NOT NULL DEFAULT 0 CHECK (advance_offset >= 0),
    other_adjustment numeric(14,2) NOT NULL DEFAULT 0,
    net_amount numeric(14,2) NOT NULL CHECK (net_amount >= 0),
    primary_advance_id bigint REFERENCES employee_advances(id),
    bank_account_id bigint REFERENCES bank_accounts(id),
    payment_method text,
    description text NOT NULL DEFAULT '',
    source_type text NOT NULL,
    source_id bigint,
    source_number text NOT NULL DEFAULT '',
    source_key text UNIQUE,
    external_transaction_id text,
    sync_source text NOT NULL DEFAULT 'manual',
    sync_status text NOT NULL DEFAULT 'local',
    reviewed_by bigint REFERENCES users(id),
    reviewed_at text,
    paid_by bigint REFERENCES users(id),
    paid_at text,
    reconciled_by bigint REFERENCES users(id),
    reconciled_at text,
    created_by bigint REFERENCES users(id),
    created_at text NOT NULL,
    updated_at text NOT NULL,
    CHECK (net_amount = gross_amount - advance_offset + other_adjustment)
);
CREATE INDEX IF NOT EXISTS idx_employee_payments_employee ON employee_payment_orders(employee_id,status);
CREATE INDEX IF NOT EXISTS idx_employee_payments_status ON employee_payment_orders(status,created_at);

CREATE TABLE IF NOT EXISTS payment_order_sources (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_order_id bigint NOT NULL REFERENCES employee_payment_orders(id) ON DELETE CASCADE,
    source_type text NOT NULL,
    source_id bigint,
    source_number text NOT NULL DEFAULT '',
    amount numeric(14,2) NOT NULL,
    created_at text NOT NULL
);

CREATE TABLE IF NOT EXISTS payment_order_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_order_id bigint NOT NULL REFERENCES employee_payment_orders(id) ON DELETE CASCADE,
    event_type text NOT NULL,
    from_status text NOT NULL DEFAULT '',
    to_status text NOT NULL DEFAULT '',
    details text NOT NULL DEFAULT '',
    created_by bigint REFERENCES users(id),
    created_at text NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_payment_events_order ON payment_order_events(payment_order_id,id);

-- Immutable signed ledger. Applications are positive; cancellation creates a
-- negative reversal row instead of editing/deleting the prior application.
CREATE TABLE IF NOT EXISTS employee_advance_applications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    advance_id bigint NOT NULL REFERENCES employee_advances(id),
    payment_order_id bigint NOT NULL REFERENCES employee_payment_orders(id),
    entry_type text NOT NULL CHECK (entry_type IN ('application','reversal')),
    amount numeric(14,2) NOT NULL CHECK (amount <> 0),
    notes text NOT NULL DEFAULT '',
    created_by bigint REFERENCES users(id),
    created_at text NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_advance_applications_advance ON employee_advance_applications(advance_id,id);
CREATE INDEX IF NOT EXISTS idx_advance_applications_payment ON employee_advance_applications(payment_order_id,id);

CREATE TABLE IF NOT EXISTS bank_transactions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank_account_id bigint NOT NULL REFERENCES bank_accounts(id),
    transaction_date text NOT NULL,
    posted_date text,
    direction text NOT NULL CHECK (direction IN ('debit','credit')),
    amount numeric(14,2) NOT NULL CHECK (amount > 0),
    currency text NOT NULL DEFAULT 'USD',
    description text NOT NULL DEFAULT '',
    reference_number text NOT NULL DEFAULT '',
    external_transaction_id text,
    sync_source text NOT NULL DEFAULT 'manual',
    sync_status text NOT NULL DEFAULT 'imported',
    import_fingerprint text NOT NULL UNIQUE,
    matched_payment_order_id bigint UNIQUE REFERENCES employee_payment_orders(id),
    matched_by bigint REFERENCES users(id),
    matched_at text,
    created_by bigint REFERENCES users(id),
    created_at text NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_bank_transactions_account_date ON bank_transactions(bank_account_id,transaction_date);
CREATE INDEX IF NOT EXISTS idx_bank_transactions_unmatched ON bank_transactions(matched_payment_order_id) WHERE matched_payment_order_id IS NULL;

CREATE TABLE IF NOT EXISTS assets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_number text NOT NULL UNIQUE,
    stable_id text NOT NULL UNIQUE,
    name text NOT NULL,
    category text NOT NULL DEFAULT '',
    acquisition_value numeric(14,2) NOT NULL DEFAULT 0 CHECK (acquisition_value >= 0),
    currency text NOT NULL DEFAULT 'USD',
    serial_number text NOT NULL DEFAULT '',
    status text NOT NULL DEFAULT 'available' CHECK (status IN ('available','assigned','damaged','lost','retired')),
    current_holder_id bigint REFERENCES users(id),
    service_order_id bigint REFERENCES service_orders(id),
    notes text NOT NULL DEFAULT '',
    created_by bigint REFERENCES users(id),
    created_at text NOT NULL,
    updated_at text NOT NULL,
    CHECK ((status = 'assigned' AND current_holder_id IS NOT NULL) OR status <> 'assigned')
);
CREATE INDEX IF NOT EXISTS idx_assets_holder ON assets(current_holder_id,status);
CREATE INDEX IF NOT EXISTS idx_assets_service_order ON assets(service_order_id);

CREATE TABLE IF NOT EXISTS asset_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id bigint NOT NULL REFERENCES assets(id) ON DELETE CASCADE,
    event_type text NOT NULL,
    from_status text NOT NULL DEFAULT '',
    to_status text NOT NULL DEFAULT '',
    holder_id bigint REFERENCES users(id),
    service_order_id bigint REFERENCES service_orders(id),
    notes text NOT NULL DEFAULT '',
    created_by bigint REFERENCES users(id),
    created_at text NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_asset_events_asset ON asset_events(asset_id,id);

CREATE TABLE IF NOT EXISTS asset_photos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id bigint NOT NULL REFERENCES assets(id) ON DELETE CASCADE,
    stored_filename text NOT NULL,
    original_filename text NOT NULL,
    created_by bigint REFERENCES users(id),
    created_at text NOT NULL
);

-- Keep the adapter's reviewed PRAGMA compatibility view aware of new objects.
INSERT INTO invoice_sqlite_columns(table_name,cid,name,type,"notnull",dflt_value,pk)
SELECT c.table_name,c.ordinal_position-1,c.column_name,c.data_type,
       CASE WHEN c.is_nullable='NO' THEN 1 ELSE 0 END,c.column_default,
       CASE WHEN EXISTS (
         SELECT 1 FROM information_schema.table_constraints tc
         JOIN information_schema.key_column_usage kcu
           ON kcu.constraint_schema=tc.constraint_schema AND kcu.constraint_name=tc.constraint_name
         WHERE tc.table_schema=c.table_schema AND tc.table_name=c.table_name
           AND tc.constraint_type='PRIMARY KEY' AND kcu.column_name=c.column_name
       ) THEN 1 ELSE 0 END
FROM information_schema.columns c
WHERE c.table_schema='public' AND c.table_name IN (
  'bank_accounts','employee_salary_agreements','employee_advances','employee_payment_orders',
  'payment_order_sources','payment_order_events','employee_advance_applications',
  'bank_transactions','assets','asset_events','asset_photos'
)
ON CONFLICT (table_name,name) DO NOTHING;

-- Internal employees may view their own payment orders. Row-level ownership is
-- enforced by the application; these grants only make the menu/page reachable.
INSERT INTO role_menu_permissions(role,menu_key,is_enabled,updated_by,updated_at)
VALUES ('employee','employee_payments',1,NULL,to_char(now() AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS"Z"'))
ON CONFLICT (role,menu_key) DO UPDATE SET is_enabled=1,updated_by=NULL,updated_at=excluded.updated_at;

INSERT INTO role_action_permissions(role,resource_key,action_key,is_enabled,updated_by,updated_at)
VALUES ('employee','employee_payments','view',1,NULL,to_char(now() AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS"Z"'))
ON CONFLICT (role,resource_key,action_key) DO UPDATE SET is_enabled=1,updated_by=NULL,updated_at=excluded.updated_at;
