-- v0.1.350 Employee payment batches: consolidate several approved payment
-- orders for the same employee into a single check / payment instruction.
-- PostgreSQL is the sole production schema. All changes are additive and
-- preserve existing rows.

CREATE TABLE IF NOT EXISTS employee_payment_batches (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_number text NOT NULL UNIQUE,
    employee_id bigint NOT NULL REFERENCES users(id),
    currency text NOT NULL DEFAULT 'USD',
    bank_account_id bigint REFERENCES bank_accounts(id),
    payment_method text NOT NULL DEFAULT 'check',
    check_number text NOT NULL DEFAULT '',
    total_amount numeric(14,2) NOT NULL DEFAULT 0 CHECK (total_amount >= 0),
    payment_count integer NOT NULL DEFAULT 0 CHECK (payment_count >= 0),
    status text NOT NULL DEFAULT 'issued'
        CHECK (status IN ('issued','reconciled','void')),
    notes text NOT NULL DEFAULT '',
    issued_by bigint REFERENCES users(id),
    issued_at text,
    reconciled_by bigint REFERENCES users(id),
    reconciled_at text,
    voided_by bigint REFERENCES users(id),
    voided_at text,
    created_at text NOT NULL,
    updated_at text NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_payment_batches_employee
    ON employee_payment_batches(employee_id,status);
CREATE INDEX IF NOT EXISTS idx_payment_batches_status
    ON employee_payment_batches(status,issued_at);

-- 一张付款单最多属于一个批次：发放批次时写入，作批次业时清空。
ALTER TABLE employee_payment_orders
    ADD COLUMN IF NOT EXISTS batch_id bigint REFERENCES employee_payment_batches(id);
CREATE INDEX IF NOT EXISTS idx_employee_payments_batch
    ON employee_payment_orders(batch_id);

-- 一张支票在银行流水里是一笔支出，整批核销（原来一笔流水只能对一张付款单）。
ALTER TABLE bank_transactions
    ADD COLUMN IF NOT EXISTS matched_batch_id bigint UNIQUE REFERENCES employee_payment_batches(id);

INSERT INTO settings(key,value)
VALUES ('postgresql_0290_payment_batches','complete')
ON CONFLICT (key) DO UPDATE SET value=excluded.value;
