-- v0.1.352 Tax classification foundation —— 第一阶段：只建结构，不改流程。
--
-- 背景：工资模块目前只有「一笔总额」。付款单（SL/ER）、员工往来账、付款批次、
-- 银行对账都只回答「钱怎么付 / 付没付」，回答不了「这笔钱在税务上属于什么」。
-- 本次把三个概念拆开：
--
--   Payment Type    这张单是工资还是报销   （已有 employee_payment_orders.payment_type）
--   Component Type  这笔钱是什么项目       （新 payroll_component_tax_config.component_code）
--   Tax Category    税务上是什么性质       （新 employee_payment_components.tax_category）
--
-- 新增 4 张表：
--   worker_tax_status_history    员工 W-2 / 1099 身份生效期历史。当前身份一律按
--                                生效日期查这张表，users 表不落当前税身份，
--                                避免出现「当前字段」与「历史表」两个真相源。
--   payroll_component_tax_config 组件默认税务分类，按 (component_code, effective_from)
--                                版本化，政策变化时加新版本而不是改旧版本。
--   employee_payment_components  付款单生成当时的组件快照。业务上 immutable：
--                                后续应用代码禁止修改原始行，人工税务调整一律写
--                                employee_payment_tax_reviews 形成覆盖 + 审计。
--   employee_payment_tax_reviews 人工复核流水（previous → new + reason），只追加不覆盖。
--
-- 扩列 3 张表：employee_payment_orders(+3 税务合计) / expenses(+3) / expense_items(+2)。
-- 新列一律 nullable 或默认 0，**不改写任何历史数据**：历史付款单三个税务合计
-- 暂时为 0，等独立的 backfill 工具确认「组件重算总额 == gross_amount」后再写入。
--
-- 明确不改：payment_order_sources、employee_payment_batches、bank_transactions、
-- 往来账/批次/对账逻辑、gross_amount / net_amount / advance_offset / other_adjustment、
-- SL/ER 编号、payroll 计算、payslip、profitability、partial payment、users 表、
-- invoice_schema_version、database.py 的 REQUIRED_* 名单。
--
-- 幂等：CREATE TABLE IF NOT EXISTS / ADD COLUMN IF NOT EXISTS / CREATE INDEX IF NOT EXISTS，
-- 默认配置用 ON CONFLICT DO NOTHING（已存在或被人工改过的行不会被覆盖），重复执行安全。
--
-- 约定沿用现有范式：日期列是 text（ISO-8601），标志位 integer 0/1，金额 numeric(14,2)。

-- ---------------------------------------------------------------------------
-- 1. 员工 W-2 / 1099 身份历史
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS worker_tax_status_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id bigint NOT NULL REFERENCES users(id),
    tax_status text NOT NULL CHECK (tax_status IN ('W2','1099')),
    effective_from text NOT NULL,
    effective_to text,
    notes text NOT NULL DEFAULT '',
    created_by bigint REFERENCES users(id),
    created_at text NOT NULL,
    CHECK (effective_to IS NULL OR effective_to >= effective_from)
    -- 生效区间重叠由应用代码校验（照 employee_salary_agreements 的既有做法），
    -- 数据库不建 exclusion constraint，避免与应用侧的提示文案重复实现。
);
CREATE INDEX IF NOT EXISTS idx_worker_tax_status_employee
    ON worker_tax_status_history(employee_id, effective_from);

-- ---------------------------------------------------------------------------
-- 2. 组件默认税务分类（版本化配置）
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS payroll_component_tax_config (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    component_code text NOT NULL,
    display_name text NOT NULL,
    default_tax_category text NOT NULL
        CHECK (default_tax_category IN
               ('taxable_compensation','accountable_reimbursement','tax_review_required')),
    requires_substantiation integer NOT NULL DEFAULT 0
        CHECK (requires_substantiation IN (0,1)),
    effective_from text NOT NULL,
    effective_to text,
    is_active integer NOT NULL DEFAULT 1 CHECK (is_active IN (0,1)),
    created_by bigint REFERENCES users(id),
    created_at text NOT NULL,
    updated_at text NOT NULL,
    CHECK (effective_to IS NULL OR effective_to >= effective_from),
    UNIQUE (component_code, effective_from)
);
CREATE INDEX IF NOT EXISTS idx_payroll_component_tax_config_lookup
    ON payroll_component_tax_config(component_code, effective_from);

-- ---------------------------------------------------------------------------
-- 3. 付款单组件快照（immutable）
--
-- source_type 只作 provenance 留痕，应用侧当前只用两个值：
--   payroll_generation   功能上线后，生成 SL/ER 的当场冻结（真正的原始快照）
--   historical_recompute 历史单据按现有源数据 + 现有算法重算出来的快照
-- 历史回填只能产生 historical_recompute：总额已验证可复现，但组件构成比例
-- 无法回到当时那一刻求证，留这个标记是为了将来知道这不是原始冻结的快照。
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS employee_payment_components (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_order_id bigint NOT NULL
        REFERENCES employee_payment_orders(id) ON DELETE CASCADE,
    employee_id bigint NOT NULL REFERENCES users(id),
    component_code text NOT NULL,
    component_name text NOT NULL DEFAULT '',
    amount numeric(14,2) NOT NULL,
    quantity numeric(14,2),
    unit text,
    unit_rate numeric(14,4),
    service_date text,
    work_order_id bigint REFERENCES service_orders(id),
    source_type text NOT NULL,
    source_id bigint,
    daily_report_id bigint REFERENCES service_reports(id),
    tax_category text NOT NULL
        CHECK (tax_category IN
               ('taxable_compensation','accountable_reimbursement','tax_review_required')),
    -- 单据开票当时的员工税身份快照；历史尚未确认时允许 NULL，之后不得回填。
    tax_status_snapshot text
        CHECK (tax_status_snapshot IS NULL OR tax_status_snapshot IN ('W2','1099')),
    -- 证明是否充分。NULL = 尚未判定，不等于「已确认不充分」。
    substantiated boolean,
    review_status text NOT NULL DEFAULT 'confirmed'
        CHECK (review_status IN ('confirmed','review_required')),
    created_at text NOT NULL,
    CHECK (service_date IS NULL OR service_date ~ '^\d{4}-\d{2}-\d{2}')
);
CREATE INDEX IF NOT EXISTS idx_payment_components_order
    ON employee_payment_components(payment_order_id);
CREATE INDEX IF NOT EXISTS idx_payment_components_employee_date
    ON employee_payment_components(employee_id, service_date);
CREATE INDEX IF NOT EXISTS idx_payment_components_tax_category
    ON employee_payment_components(tax_category);
CREATE INDEX IF NOT EXISTS idx_payment_components_tax_status
    ON employee_payment_components(tax_status_snapshot);
CREATE INDEX IF NOT EXISTS idx_payment_components_review
    ON employee_payment_components(review_status);

-- ---------------------------------------------------------------------------
-- 4. 人工税务复核审计（只追加）
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS employee_payment_tax_reviews (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    component_id bigint NOT NULL
        REFERENCES employee_payment_components(id) ON DELETE CASCADE,
    reviewed_by bigint NOT NULL REFERENCES users(id),
    reviewed_at text NOT NULL,
    previous_tax_category text
        CHECK (previous_tax_category IS NULL OR previous_tax_category IN
               ('taxable_compensation','accountable_reimbursement','tax_review_required')),
    new_tax_category text NOT NULL
        CHECK (new_tax_category IN
               ('taxable_compensation','accountable_reimbursement','tax_review_required')),
    reason text NOT NULL CHECK (btrim(reason) <> ''),
    CONSTRAINT employee_payment_tax_reviews_category_changed
        CHECK (previous_tax_category IS DISTINCT FROM new_tax_category)
);
CREATE INDEX IF NOT EXISTS idx_payment_tax_reviews_component
    ON employee_payment_tax_reviews(component_id);

-- ---------------------------------------------------------------------------
-- 5. employee_payment_orders：三个税务合计（总额仍然只读 gross_amount）
--
-- 应用代码必须保证：
--   gross_amount = taxable_compensation_total
--                + accountable_reimbursement_total
--                + tax_review_required_total
-- 迁移不建该约束（历史行三个字段都是 0，会被 CHECK 一次性打穿），
-- 也不批量回填历史值。
-- ---------------------------------------------------------------------------
ALTER TABLE employee_payment_orders
    ADD COLUMN IF NOT EXISTS taxable_compensation_total numeric(14,2) NOT NULL DEFAULT 0;
ALTER TABLE employee_payment_orders
    ADD COLUMN IF NOT EXISTS accountable_reimbursement_total numeric(14,2) NOT NULL DEFAULT 0;
ALTER TABLE employee_payment_orders
    ADD COLUMN IF NOT EXISTS tax_review_required_total numeric(14,2) NOT NULL DEFAULT 0;

-- ---------------------------------------------------------------------------
-- 6. expenses / expense_items：税务属性
--
-- 全部 nullable —— NULL 表示「尚未分类」，绝不能当成 false 或 taxable；
-- 缺分类的历史记录必须走 tax_review_required，不允许靠分类名猜
-- （禁止复用 is_lodging_project_name / is_fuel_project_name 这类按名字判断的函数）。
-- ---------------------------------------------------------------------------
ALTER TABLE expenses
    ADD COLUMN IF NOT EXISTS business_purpose text;
ALTER TABLE expenses
    ADD COLUMN IF NOT EXISTS substantiated boolean;
ALTER TABLE expenses
    ADD COLUMN IF NOT EXISTS tax_category text
        CHECK (tax_category IS NULL OR tax_category IN
               ('taxable_compensation','accountable_reimbursement','tax_review_required'));

ALTER TABLE expense_items
    ADD COLUMN IF NOT EXISTS tax_category text
        CHECK (tax_category IS NULL OR tax_category IN
               ('taxable_compensation','accountable_reimbursement','tax_review_required'));
ALTER TABLE expense_items
    ADD COLUMN IF NOT EXISTS substantiated boolean;

-- ---------------------------------------------------------------------------
-- 7. 组件默认税务分类
--
-- self_drive_allowance 默认 accountable_reimbursement，但 requires_substantiation=1：
-- 缺 mileage evidence / business purpose / work order 时由应用代码降级成
-- tax_review_required，不得直接认定免税。
-- meal_allowance 暂不自动认定免税，默认 tax_review_required，等 CPA 确认。
-- report_writing_fee（复杂日报 $20/次）按 taxable_compensation，不走 de minimis。
-- 已有行不会被覆盖（ON CONFLICT DO NOTHING），后续政策调整走新版本行。
-- ---------------------------------------------------------------------------
INSERT INTO payroll_component_tax_config
    (component_code, display_name, default_tax_category, requires_substantiation,
     effective_from, effective_to, is_active, created_at, updated_at)
VALUES
    ('standard_pay','标准工资','taxable_compensation',0,'2020-01-01',NULL,1,
     to_char(now(), 'YYYY-MM-DD"T"HH24:MI:SSOF'), to_char(now(), 'YYYY-MM-DD"T"HH24:MI:SSOF')),
    ('overtime_pay','加班工资','taxable_compensation',0,'2020-01-01',NULL,1,
     to_char(now(), 'YYYY-MM-DD"T"HH24:MI:SSOF'), to_char(now(), 'YYYY-MM-DD"T"HH24:MI:SSOF')),
    ('holiday_pay','假期工资','taxable_compensation',0,'2020-01-01',NULL,1,
     to_char(now(), 'YYYY-MM-DD"T"HH24:MI:SSOF'), to_char(now(), 'YYYY-MM-DD"T"HH24:MI:SSOF')),
    ('following_allowance','随行补贴','taxable_compensation',0,'2020-01-01',NULL,1,
     to_char(now(), 'YYYY-MM-DD"T"HH24:MI:SSOF'), to_char(now(), 'YYYY-MM-DD"T"HH24:MI:SSOF')),
    ('rental_driving_allowance','租车驾驶补贴','taxable_compensation',0,'2020-01-01',NULL,1,
     to_char(now(), 'YYYY-MM-DD"T"HH24:MI:SSOF'), to_char(now(), 'YYYY-MM-DD"T"HH24:MI:SSOF')),
    ('self_drive_allowance','自驾车补','accountable_reimbursement',1,'2020-01-01',NULL,1,
     to_char(now(), 'YYYY-MM-DD"T"HH24:MI:SSOF'), to_char(now(), 'YYYY-MM-DD"T"HH24:MI:SSOF')),
    ('report_writing_fee','复杂日报补贴','taxable_compensation',0,'2020-01-01',NULL,1,
     to_char(now(), 'YYYY-MM-DD"T"HH24:MI:SSOF'), to_char(now(), 'YYYY-MM-DD"T"HH24:MI:SSOF')),
    ('base_salary','基本工资','taxable_compensation',0,'2020-01-01',NULL,1,
     to_char(now(), 'YYYY-MM-DD"T"HH24:MI:SSOF'), to_char(now(), 'YYYY-MM-DD"T"HH24:MI:SSOF')),
    ('meal_allowance','餐补','tax_review_required',0,'2020-01-01',NULL,1,
     to_char(now(), 'YYYY-MM-DD"T"HH24:MI:SSOF'), to_char(now(), 'YYYY-MM-DD"T"HH24:MI:SSOF'))
ON CONFLICT (component_code, effective_from) DO NOTHING;

INSERT INTO settings(key,value)
VALUES ('postgresql_0291_tax_classification','complete')
ON CONFLICT (key) DO UPDATE SET value=excluded.value;
