-- v0.1.360 Quotation / 报价单。
--
-- 报价单是独立于合同的销售前文档：网页填写，直接导出 PDF（Prasinos Power
-- Quote Template v2 版式）。表结构对齐模板字段：
--   * 基本信息（编号 / 日期 / 有效期 / 编制人 / 客户 / 联系人 / 项目 / PO）；
--   * 工作范围（项目描述 + 3 条范围）；
--   * 定价汇总 8 行（数量 / 单位 / 费率 / 金额，JSON 存 pricing_lines）；
--   * 小计 / 税 / 总计（后端计算，前端展示）；
--   * 费率表 9 行（rate_schedule JSON）；
--   * 项目假设、付款与开票；
-- 差旅费用表在模板中是固定文案，PDF 生成时直接渲染，不落库。
--
-- 幂等：CREATE TABLE IF NOT EXISTS，重复执行安全。
-- 明确不改：任何既有表 / 既有行。

CREATE TABLE IF NOT EXISTS quotations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quotation_number text NOT NULL UNIQUE,
    quotation_date text NOT NULL,
    valid_until text NOT NULL,
    prepared_by text NOT NULL DEFAULT '',
    customer text NOT NULL DEFAULT '',
    contact text NOT NULL DEFAULT '',
    project_name text NOT NULL DEFAULT '',
    project_no text NOT NULL DEFAULT '',
    project_location text NOT NULL DEFAULT '',
    po_no text NOT NULL DEFAULT '',
    status text NOT NULL DEFAULT 'draft'
        CHECK (status IN ('draft','sent','accepted','expired','cancelled')),
    currency text NOT NULL DEFAULT 'USD',
    project_description text NOT NULL DEFAULT '',
    scope_1 text NOT NULL DEFAULT '',
    scope_2 text NOT NULL DEFAULT '',
    scope_3 text NOT NULL DEFAULT '',
    pricing_lines text NOT NULL DEFAULT '[]',
    subtotal numeric(14,2) NOT NULL DEFAULT 0,
    tax numeric(14,2) NOT NULL DEFAULT 0,
    total numeric(14,2) NOT NULL DEFAULT 0,
    rate_schedule text NOT NULL DEFAULT '[]',
    crew_size text NOT NULL DEFAULT '',
    workdays text NOT NULL DEFAULT '',
    hours_per_day text NOT NULL DEFAULT '',
    expected_start_date text NOT NULL DEFAULT '',
    expected_completion text NOT NULL DEFAULT '',
    normal_working_hours text NOT NULL DEFAULT '',
    customer_provides text NOT NULL DEFAULT '',
    assumptions_other text NOT NULL DEFAULT '',
    payment_terms text NOT NULL DEFAULT 'net_30'
        CHECK (payment_terms IN ('net_15','net_30','net_45','other')),
    payment_terms_other text NOT NULL DEFAULT '',
    quotation_validity text NOT NULL DEFAULT '30 calendar days',
    invoice_frequency text NOT NULL DEFAULT 'upon_completion'
        CHECK (invoice_frequency IN ('weekly','biweekly','monthly','upon_completion')),
    pricing_type text NOT NULL DEFAULT 'estimated'
        CHECK (pricing_type IN ('fixed','estimated')),
    tax_note text NOT NULL DEFAULT 'Excluded unless stated',
    notes text NOT NULL DEFAULT '',
    created_by bigint NOT NULL REFERENCES users(id),
    created_at text NOT NULL,
    updated_at text NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_quotations_number ON quotations(quotation_number);
CREATE INDEX IF NOT EXISTS idx_quotations_status ON quotations(status);
CREATE INDEX IF NOT EXISTS idx_quotations_created_at ON quotations(created_at);

-- 可选关联正式客户（clients 表）：工单引用报价单时做客户一致性校验。
ALTER TABLE quotations ADD COLUMN IF NOT EXISTS client_id bigint REFERENCES clients(id);

-- 工单可引用报价单（与关联合同并列）。只新增可空外键，不改既有行。
ALTER TABLE service_orders ADD COLUMN IF NOT EXISTS quotation_id bigint REFERENCES quotations(id);
CREATE INDEX IF NOT EXISTS idx_service_orders_quotation_id ON service_orders(quotation_id);

INSERT INTO settings(key,value)
VALUES ('postgresql_0295_quotations','complete')
ON CONFLICT (key) DO UPDATE SET value=excluded.value;
