-- Payroll Cycle Correction allocation layer (Option C).
--
-- Formal payroll cycle anchor is settings.payroll_cycle_start = 2026-07-06 and
-- then rolls forward every 14 days. Historical salary payment orders were
-- generated with off-grid period labels, so 07-06..09-27 needs correcting to
-- the canonical grid.
--
-- Design contract (do not "simplify" without re-reading the correction plan):
--   * employee_payment_components stays a frozen immutable snapshot: id,
--     payment_order_id, amount, service_date and every source identity column
--     keep their historical values forever. Nothing here re-parents a
--     component and nothing deletes a component.
--   * canonical membership is expressed ONLY by rows in
--     payroll_component_correction_allocations. duplicate_superseded rows stop
--     counting towards effective payroll; every other disposition keeps its
--     historical amount and is attributed to
--     coalesce(canonical_payment_order_id, payment_order_id).
--   * With zero rows in these tables every read path behaves exactly as it
--     does today, which is what makes the migration deploy-safe ahead of the
--     correction itself.
--
-- Additive and idempotent: no existing row or column is modified.

-- ---------------------------------------------------------------------------
-- 1. Correction group: the correction run itself.
--    Metadata lives here once instead of being repeated on every allocation
--    row (policy version, canonical grid parameters, reason, lifecycle).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS payroll_correction_groups (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Stable slug used by code and tests, e.g. payroll_cycle_realignment_2026.
    correction_code text NOT NULL UNIQUE,
    correction_type text NOT NULL DEFAULT 'payroll_cycle_realignment'
        CHECK (correction_type IN ('payroll_cycle_realignment', 'other')),
    -- Classification policy applied to correction-generated rows,
    -- e.g. phase6d_company_policy_2026.
    policy_version text NOT NULL DEFAULT '',
    canonical_cycle_start text,
    canonical_cycle_days integer NOT NULL DEFAULT 14
        CHECK (canonical_cycle_days > 0),
    canonical_period_start text,
    canonical_period_end text,
    status text NOT NULL DEFAULT 'draft'
        CHECK (status IN ('draft', 'applied', 'rolled_back')),
    reason text NOT NULL DEFAULT '',
    created_by bigint REFERENCES users(id),
    created_at text NOT NULL,
    updated_at text NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_payroll_correction_groups_status
    ON payroll_correction_groups(status, correction_code);

-- ---------------------------------------------------------------------------
-- 2. Payment-order correction lifecycle (minimal: 4 columns).
--    replacement_of_id is intentionally absent: it is the inverse of
--    superseded_by_id and would let the two columns drift apart.
-- ---------------------------------------------------------------------------
ALTER TABLE employee_payment_orders
    ADD COLUMN IF NOT EXISTS correction_status text NOT NULL DEFAULT 'none';
ALTER TABLE employee_payment_orders
    ADD COLUMN IF NOT EXISTS correction_group_id bigint;
ALTER TABLE employee_payment_orders
    ADD COLUMN IF NOT EXISTS superseded_by_id bigint;
ALTER TABLE employee_payment_orders
    ADD COLUMN IF NOT EXISTS correction_reason text NOT NULL DEFAULT '';
-- NOTE: no canonical_period_* columns here on purpose. A replacement SL's
-- period already lives in source_number ("YYYY-MM-DD~YYYY-MM-DD") — duplicating
-- it as columns would give us two places that can disagree. The authoritative
-- per-component period lives on the allocation row.

-- Named constraints are not idempotent on their own; guard the DDL so the file
-- can be replayed on an already-upgraded database.
DO $do$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'ck_employee_payments_correction_status'
          AND conrelid = 'employee_payment_orders'::regclass
    ) THEN
        ALTER TABLE employee_payment_orders
            ADD CONSTRAINT ck_employee_payments_correction_status
            CHECK (correction_status IN (
                'none',
                'correction_pending',
                'partially_superseded',
                'superseded',
                'replacement',
                'period_label_corrected'
            ));
    END IF;
END
$do$;

DO $do$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_employee_payments_correction_group'
          AND conrelid = 'employee_payment_orders'::regclass
    ) THEN
        ALTER TABLE employee_payment_orders
            ADD CONSTRAINT fk_employee_payments_correction_group
            FOREIGN KEY (correction_group_id)
            REFERENCES payroll_correction_groups(id);
    END IF;
END
$do$;

DO $do$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_employee_payments_superseded_by'
          AND conrelid = 'employee_payment_orders'::regclass
    ) THEN
        ALTER TABLE employee_payment_orders
            ADD CONSTRAINT fk_employee_payments_superseded_by
            FOREIGN KEY (superseded_by_id)
            REFERENCES employee_payment_orders(id);
    END IF;
END
$do$;

CREATE INDEX IF NOT EXISTS idx_employee_payments_correction_status
    ON employee_payment_orders(correction_status);
CREATE INDEX IF NOT EXISTS idx_employee_payments_correction_group
    ON employee_payment_orders(correction_group_id);

-- ---------------------------------------------------------------------------
-- 3. Component correction allocations: Original Parent vs Effective Canonical
--    Allocation. This table is the single source of truth for post-correction
--    payroll detail; employee_payment_components.superseded_at keeps serving
--    the expense side only.
--
--    disposition
--      retained              amount is correct, only re-attributed to another
--                            canonical period / replacement SL
--      duplicate_superseded  true duplicate; no longer counted anywhere
--      carry_forward         belongs to a still-open future period
--                            (e.g. 2026-09-29 -> P7 09-28~10-11)
--      pre_canonical_legacy  before the canonical anchor; out of scope and
--                            left exactly as generated
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS payroll_component_correction_allocations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    correction_group_id bigint NOT NULL REFERENCES payroll_correction_groups(id),
    -- The frozen component row itself; never updated by this layer.
    component_id bigint NOT NULL REFERENCES employee_payment_components(id),
    -- Canonical payment order this component now reports under. NULL means
    -- "no new payable" (already-paid corrections) or "not yet generated"
    -- (carry_forward), in which case the original order stays authoritative.
    canonical_payment_order_id bigint REFERENCES employee_payment_orders(id),
    canonical_period_start text,
    canonical_period_end text,
    disposition text NOT NULL
        CHECK (disposition IN (
            'retained',
            'duplicate_superseded',
            'carry_forward',
            'pre_canonical_legacy'
        )),
    -- Populated only on duplicate_superseded rows: the sibling snapshot that
    -- survives. Retained rows are their own keeper.
    keeper_component_id bigint REFERENCES employee_payment_components(id),
    reason text NOT NULL DEFAULT '',
    created_by bigint REFERENCES users(id),
    created_at text NOT NULL,
    CONSTRAINT uq_correction_allocation_component
        UNIQUE (correction_group_id, component_id),
    -- The 14-day grid is pinned here, but it must only bite rows that actually
    -- carry a canonical window; legacy / metadata rows keep both NULL.
    CONSTRAINT ck_correction_allocation_canonical_period
        CHECK ((canonical_period_start IS NULL AND canonical_period_end IS NULL)
               OR (canonical_period_start IS NOT NULL
                   AND canonical_period_end IS NOT NULL
                   AND (canonical_period_end::date - canonical_period_start::date) = 13)),
    CONSTRAINT ck_correction_allocation_keeper
        CHECK (CASE disposition
                    WHEN 'duplicate_superseded' THEN keeper_component_id IS NOT NULL
                    ELSE keeper_component_id IS NULL
               END)
);
CREATE INDEX IF NOT EXISTS idx_corr_alloc_component
    ON payroll_component_correction_allocations(component_id);
CREATE INDEX IF NOT EXISTS idx_corr_alloc_canonical_order
    ON payroll_component_correction_allocations(canonical_payment_order_id);
CREATE INDEX IF NOT EXISTS idx_corr_alloc_disposition
    ON payroll_component_correction_allocations(disposition);
CREATE INDEX IF NOT EXISTS idx_corr_alloc_group
    ON payroll_component_correction_allocations(correction_group_id, disposition);

INSERT INTO settings(key,value)
VALUES ('postgresql_0297_payroll_cycle_correction','complete')
ON CONFLICT (key) DO UPDATE SET value=excluded.value;
