-- Accounting base schema, phase 1.
-- Additive and disabled by default: this migration creates no vouchers and
-- does not alter any existing business fact.

CREATE TABLE IF NOT EXISTS accounts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_code text NOT NULL UNIQUE,
    account_name text NOT NULL,
    account_type text NOT NULL
        CHECK (account_type IN ('asset','liability','equity','revenue','expense')),
    normal_balance text NOT NULL CHECK (normal_balance IN ('debit','credit')),
    currency text NOT NULL DEFAULT 'USD' CHECK (currency = 'USD'),
    is_system boolean NOT NULL DEFAULT true,
    is_active boolean NOT NULL DEFAULT true,
    created_at text NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    CHECK ((account_type IN ('asset','expense') AND normal_balance = 'debit') OR
           (account_type IN ('liability','equity','revenue') AND normal_balance = 'credit'))
);

INSERT INTO accounts(account_code,account_name,account_type,normal_balance)
VALUES
 ('1000','Bank','asset','debit'),
 ('1100','Accounts Receivable','asset','debit'),
 ('1200','Employee Advances','asset','debit'),
 ('2000','Employee Payable','liability','credit'),
 ('2100','Sales Tax Payable','liability','credit'),
 ('2200','Customer Prepayments','liability','credit'),
 ('3000','Opening Balance Equity','equity','credit'),
 ('4000','Revenue','revenue','credit'),
 ('5000','Expense','expense','debit'),
 ('5100','Bank Fees','expense','debit')
ON CONFLICT (account_code) DO NOTHING;

CREATE TABLE IF NOT EXISTS accounting_periods (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    period_start date NOT NULL,
    period_end date NOT NULL,
    status text NOT NULL DEFAULT 'open' CHECK (status IN ('open','closed')),
    closed_by bigint REFERENCES users(id),
    closed_at text,
    reopened_by bigint REFERENCES users(id),
    reopened_at text,
    reason_code text NOT NULL DEFAULT '',
    created_at text NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    UNIQUE(period_start,period_end),
    CHECK (period_end >= period_start)
);

CREATE TABLE IF NOT EXISTS vouchers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voucher_number text NOT NULL UNIQUE,
    voucher_type text NOT NULL,
    status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','posted','reversed')),
    business_date date NOT NULL,
    accounting_date date NOT NULL,
    currency text NOT NULL DEFAULT 'USD' CHECK (currency = 'USD'),
    description text NOT NULL DEFAULT '',
    source_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
    reversal_of bigint REFERENCES vouchers(id),
    corrects_opening_line bigint,
    reason_code text NOT NULL DEFAULT '',
    created_by bigint REFERENCES users(id),
    created_at text NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    posted_by bigint REFERENCES users(id),
    posted_at text,
    reversed_by bigint REFERENCES users(id),
    reversed_at text,
    CHECK (id IS DISTINCT FROM reversal_of)
);

CREATE TABLE IF NOT EXISTS posting_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_type text NOT NULL,
    source_id bigint NOT NULL,
    -- Second member of compound business keys (advance/payment,
    -- bank-transaction/target). Zero denotes a single-object event.
    related_source_id bigint NOT NULL DEFAULT 0,
    source_version bigint NOT NULL CHECK (source_version >= 1),
    event_type text NOT NULL,
    occurrence_no integer NOT NULL CHECK (occurrence_no >= 1),
    requires_gl boolean NOT NULL,
    payload_hash text NOT NULL CHECK (payload_hash ~ '^[0-9a-f]{64}$'),
    business_anchor_type text NOT NULL,
    business_anchor_id bigint NOT NULL,
    idempotency_key text,
    voucher_id bigint REFERENCES vouchers(id),
    created_by bigint REFERENCES users(id),
    created_at text NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    CHECK ((requires_gl AND voucher_id IS NOT NULL) OR
           (NOT requires_gl AND voucher_id IS NULL))
);
ALTER TABLE posting_events
    ADD COLUMN IF NOT EXISTS related_source_id bigint NOT NULL DEFAULT 0;
DO $do$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint
                   WHERE conname='ck_posting_events_related_source_id'
                     AND conrelid='posting_events'::regclass) THEN
        ALTER TABLE posting_events ADD CONSTRAINT ck_posting_events_related_source_id
            CHECK (related_source_id >= 0);
    END IF;
END $do$;

ALTER TABLE posting_events DROP CONSTRAINT IF EXISTS
    posting_events_source_type_source_id_source_version_event_t_key;
CREATE UNIQUE INDEX IF NOT EXISTS uq_posting_events_business_event
    ON posting_events(source_type,source_id,related_source_id,source_version,event_type,occurrence_no);
CREATE UNIQUE INDEX IF NOT EXISTS uq_posting_events_idempotency_key
    ON posting_events(idempotency_key) WHERE idempotency_key IS NOT NULL;

CREATE TABLE IF NOT EXISTS voucher_entries (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voucher_id bigint NOT NULL REFERENCES vouchers(id),
    line_no integer NOT NULL CHECK (line_no >= 1),
    account_id bigint NOT NULL REFERENCES accounts(id),
    debit numeric(14,2) NOT NULL DEFAULT 0 CHECK (debit >= 0),
    credit numeric(14,2) NOT NULL DEFAULT 0 CHECK (credit >= 0),
    currency text NOT NULL DEFAULT 'USD' CHECK (currency = 'USD'),
    source_line_type text NOT NULL DEFAULT '',
    source_line_id bigint,
    memo text NOT NULL DEFAULT '',
    created_at text NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    UNIQUE(voucher_id,line_no),
    CHECK ((debit > 0 AND credit = 0) OR (credit > 0 AND debit = 0))
);

CREATE TABLE IF NOT EXISTS voucher_source_links (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voucher_id bigint NOT NULL REFERENCES vouchers(id),
    source_type text NOT NULL,
    source_id bigint NOT NULL,
    source_version bigint NOT NULL CHECK (source_version >= 1),
    created_at text NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    UNIQUE(voucher_id,source_type,source_id,source_version)
);

CREATE TABLE IF NOT EXISTS voucher_attachment_links (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voucher_id bigint NOT NULL REFERENCES vouchers(id),
    source_type text NOT NULL,
    source_id bigint NOT NULL,
    content_sha256 text NOT NULL CHECK (content_sha256 ~ '^[0-9a-f]{64}$'),
    stored_filename text NOT NULL,
    byte_size bigint NOT NULL CHECK (byte_size >= 0),
    row_version bigint NOT NULL CHECK (row_version >= 1),
    captured_at text NOT NULL,
    UNIQUE(voucher_id,source_type,source_id,row_version)
);

CREATE TABLE IF NOT EXISTS voucher_settlement_lines (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voucher_id bigint NOT NULL REFERENCES vouchers(id),
    voucher_entry_id bigint NOT NULL REFERENCES voucher_entries(id),
    target_type text NOT NULL CHECK (target_type IN ('payable','receivable','prepayment')),
    target_id bigint NOT NULL,
    amount numeric(14,2) NOT NULL CHECK (amount > 0),
    status text NOT NULL DEFAULT 'active' CHECK (status IN ('active','reversed','redirected')),
    reversed_by bigint REFERENCES voucher_settlement_lines(id),
    redirected_to bigint REFERENCES voucher_settlement_lines(id),
    currency text NOT NULL DEFAULT 'USD' CHECK (currency = 'USD'),
    source_event_id bigint NOT NULL REFERENCES posting_events(id),
    created_at text NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    UNIQUE(voucher_entry_id,source_event_id),
    CHECK (id IS DISTINCT FROM reversed_by AND id IS DISTINCT FROM redirected_to)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_active_voucher_settlement_target_event
    ON voucher_settlement_lines(target_type,target_id,source_event_id)
    WHERE status = 'active';

CREATE TABLE IF NOT EXISTS accounting_opening_cutover (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cutover_date date NOT NULL UNIQUE,
    status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','posted')),
    voucher_id bigint REFERENCES vouchers(id),
    created_by bigint REFERENCES users(id),
    created_at text NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    posted_by bigint REFERENCES users(id),
    posted_at text
);

CREATE TABLE IF NOT EXISTS accounting_opening_lines (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cutover_id bigint NOT NULL REFERENCES accounting_opening_cutover(id),
    origin_type text NOT NULL,
    origin_id bigint NOT NULL,
    account_id bigint NOT NULL REFERENCES accounts(id),
    amount numeric(14,2) NOT NULL CHECK (amount > 0),
    currency text NOT NULL DEFAULT 'USD' CHECK (currency = 'USD'),
    reason_code text NOT NULL CHECK (reason_code IN
        ('prior_period_error','post_cutover_new','cutover_reclassification')),
    voucher_entry_id bigint REFERENCES voucher_entries(id),
    created_at text NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    UNIQUE(origin_type,origin_id)
);
ALTER TABLE vouchers DROP CONSTRAINT IF EXISTS vouchers_corrects_opening_line_fkey;
ALTER TABLE vouchers ADD CONSTRAINT vouchers_corrects_opening_line_fkey
    FOREIGN KEY (corrects_opening_line) REFERENCES accounting_opening_lines(id);

CREATE TABLE IF NOT EXISTS posting_audit (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    posting_event_id bigint REFERENCES posting_events(id),
    voucher_id bigint REFERENCES vouchers(id),
    action text NOT NULL,
    old_value jsonb,
    new_value jsonb,
    reason_code text NOT NULL DEFAULT '',
    actor_id bigint REFERENCES users(id),
    created_at text NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE TABLE IF NOT EXISTS customer_receipts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_no text NOT NULL,
    customer_id bigint NOT NULL REFERENCES clients(id),
    receipt_date date NOT NULL,
    amount numeric(14,2) NOT NULL CHECK (amount > 0),
    currency text NOT NULL DEFAULT 'USD' CHECK (currency = 'USD'),
    bank_account_id bigint NOT NULL REFERENCES bank_accounts(id),
    reason_code text NOT NULL DEFAULT '',
    posting_event_id bigint REFERENCES posting_events(id),
    voucher_id bigint REFERENCES vouchers(id),
    created_by bigint REFERENCES users(id),
    created_at text NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    UNIQUE(customer_id,receipt_no)
);

CREATE TABLE IF NOT EXISTS receipt_allocations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_id bigint NOT NULL REFERENCES customer_receipts(id),
    invoice_id bigint NOT NULL REFERENCES invoices(id),
    amount numeric(14,2) NOT NULL CHECK (amount > 0),
    currency text NOT NULL DEFAULT 'USD' CHECK (currency = 'USD'),
    status text NOT NULL DEFAULT 'active' CHECK (status IN ('active','reversed','redirected')),
    reversed_by bigint REFERENCES receipt_allocations(id),
    redirected_to bigint REFERENCES receipt_allocations(id),
    source_event_id bigint REFERENCES posting_events(id),
    created_at text NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    CHECK (id IS DISTINCT FROM reversed_by AND id IS DISTINCT FROM redirected_to)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_active_receipt_invoice_allocation
    ON receipt_allocations(receipt_id,invoice_id) WHERE status = 'active';

CREATE TABLE IF NOT EXISTS customer_prepayments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id bigint NOT NULL REFERENCES clients(id),
    receipt_id bigint NOT NULL REFERENCES customer_receipts(id),
    original_amount numeric(14,2) NOT NULL CHECK (original_amount > 0),
    currency text NOT NULL DEFAULT 'USD' CHECK (currency = 'USD'),
    reason_code text NOT NULL CHECK (reason_code <> ''),
    status text NOT NULL DEFAULT 'open' CHECK (status IN ('open','applied','reversed')),
    posting_event_id bigint REFERENCES posting_events(id),
    voucher_id bigint REFERENCES vouchers(id),
    created_at text NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    UNIQUE(receipt_id)
);

CREATE TABLE IF NOT EXISTS accounting_base_check_report (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    checked_at text NOT NULL,
    schema_ok boolean NOT NULL,
    report jsonb NOT NULL,
    saved_by bigint REFERENCES users(id),
    created_at text NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

ALTER TABLE employee_advance_applications
    ADD COLUMN IF NOT EXISTS posting_event_id bigint REFERENCES posting_events(id);
ALTER TABLE employee_advance_applications
    ADD COLUMN IF NOT EXISTS voucher_id bigint REFERENCES vouchers(id);
ALTER TABLE employee_advance_applications
    ADD COLUMN IF NOT EXISTS occurrence_no integer;
ALTER TABLE employee_advance_applications
    ADD COLUMN IF NOT EXISTS legacy_anchor boolean NOT NULL DEFAULT false;
CREATE UNIQUE INDEX IF NOT EXISTS uq_advance_application_occurrence
    ON employee_advance_applications(advance_id,payment_order_id,occurrence_no)
    WHERE occurrence_no IS NOT NULL;

CREATE OR REPLACE FUNCTION protect_posted_voucher_child() RETURNS trigger AS $$
DECLARE old_voucher_id bigint; new_voucher_id bigint;
BEGIN
    old_voucher_id := CASE WHEN TG_OP IN ('UPDATE','DELETE') THEN OLD.voucher_id ELSE NULL END;
    new_voucher_id := CASE WHEN TG_OP IN ('INSERT','UPDATE') THEN NEW.voucher_id ELSE NULL END;
    IF EXISTS (SELECT 1 FROM vouchers
               WHERE id IN (old_voucher_id,new_voucher_id) AND status='posted') THEN
        RAISE EXCEPTION 'posted voucher children are immutable';
    END IF;
    RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
END $$ LANGUAGE plpgsql;

DO $do$ DECLARE table_name text;
BEGIN
  FOREACH table_name IN ARRAY ARRAY['voucher_entries','voucher_source_links',
      'voucher_attachment_links','voucher_settlement_lines'] LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS %I ON %I', table_name || '_protect_posted', table_name);
    EXECUTE format('CREATE TRIGGER %I BEFORE INSERT OR UPDATE OR DELETE ON %I '
                   'FOR EACH ROW EXECUTE FUNCTION protect_posted_voucher_child()',
                   table_name || '_protect_posted', table_name);
  END LOOP;
END $do$;

-- Test isolation uses TRUNCATE ... RESTART IDENTITY and therefore requires
-- ownership, not merely TRUNCATE/sequence grants. Never apply this ownership
-- transfer outside the explicitly named disposable test database.
DO $do$
DECLARE table_name text;
DECLARE base_tables text[] := ARRAY[
  'accounts','accounting_periods','posting_events','vouchers','voucher_entries',
  'voucher_source_links','voucher_settlement_lines','voucher_attachment_links',
  'accounting_opening_lines','accounting_opening_cutover','posting_audit',
  'customer_receipts','receipt_allocations','customer_prepayments',
  'accounting_base_check_report'
];
BEGIN
  IF current_database() = 'invoice_test'
     AND EXISTS (SELECT 1 FROM pg_roles WHERE rolname='invoice_test') THEN
    FOREACH table_name IN ARRAY base_tables LOOP
      EXECUTE format('ALTER TABLE %I OWNER TO invoice_test',table_name);
    END LOOP;
  END IF;
END $do$;

CREATE OR REPLACE FUNCTION guard_voucher_mutation() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'DELETE' AND OLD.status IN ('posted','reversed') THEN
        RAISE EXCEPTION 'posted or reversed vouchers cannot be deleted';
    END IF;
    IF TG_OP = 'UPDATE' AND OLD.status = 'posted' THEN
        IF NEW.status <> 'reversed' OR NEW.reversed_at IS NULL OR
           NEW.reversed_by IS NULL OR NEW.reason_code = '' OR
           (to_jsonb(NEW) - ARRAY['status','reversed_by','reversed_at','reason_code']) <>
           (to_jsonb(OLD) - ARRAY['status','reversed_by','reversed_at','reason_code']) THEN
            RAISE EXCEPTION 'illegal posted voucher mutation';
        END IF;
    ELSIF TG_OP = 'UPDATE' AND OLD.status = 'reversed' AND to_jsonb(NEW) <> to_jsonb(OLD) THEN
        RAISE EXCEPTION 'reversed vouchers are immutable';
    ELSIF TG_OP = 'UPDATE' AND OLD.status = 'draft' AND NEW.status NOT IN ('draft','posted') THEN
        RAISE EXCEPTION 'illegal voucher status transition: % -> %', OLD.status, NEW.status;
    END IF;
    RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
END $$ LANGUAGE plpgsql;
DROP TRIGGER IF EXISTS vouchers_mutation_guard ON vouchers;
CREATE TRIGGER vouchers_mutation_guard BEFORE UPDATE OR DELETE ON vouchers
    FOR EACH ROW EXECUTE FUNCTION guard_voucher_mutation();

CREATE OR REPLACE FUNCTION enforce_voucher_balance() RETURNS trigger AS $$
DECLARE target_id bigint; debits numeric(14,2); credits numeric(14,2);
BEGIN
    IF TG_TABLE_NAME = 'vouchers' THEN
        IF TG_OP = 'DELETE' THEN target_id := OLD.id; ELSE target_id := NEW.id; END IF;
    ELSE
        IF TG_OP = 'DELETE' THEN target_id := OLD.voucher_id;
        ELSE target_id := NEW.voucher_id;
        END IF;
    END IF;
    IF EXISTS (SELECT 1 FROM vouchers WHERE id=target_id AND status IN ('posted','reversed')) THEN
        SELECT COALESCE(sum(debit),0),COALESCE(sum(credit),0)
          INTO debits,credits FROM voucher_entries WHERE voucher_id=target_id;
        IF debits = 0 OR debits <> credits THEN
            RAISE EXCEPTION 'voucher % is not balanced: debit %, credit %',target_id,debits,credits;
        END IF;
    END IF;
    RETURN NULL;
END $$ LANGUAGE plpgsql;
DROP TRIGGER IF EXISTS voucher_entries_balance_check ON voucher_entries;
CREATE CONSTRAINT TRIGGER voucher_entries_balance_check
    AFTER INSERT OR UPDATE OR DELETE ON voucher_entries
    DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION enforce_voucher_balance();
DROP TRIGGER IF EXISTS vouchers_balance_check ON vouchers;
CREATE CONSTRAINT TRIGGER vouchers_balance_check
    AFTER INSERT OR UPDATE OF status ON vouchers
    DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION enforce_voucher_balance();

INSERT INTO settings(key,value) VALUES ('accounting_base_enabled','0')
ON CONFLICT (key) DO NOTHING;
INSERT INTO settings(key,value) VALUES ('postgresql_0298_accounting_base','complete')
ON CONFLICT (key) DO UPDATE SET value=excluded.value;

-- The application can perform ordinary DML but cannot own these tables,
-- alter them, disable triggers, or create triggers. The dedicated test role,
-- when present, receives test-only cleanup privileges.
DO $do$
DECLARE role_name text; table_name text; sequence_name text;
DECLARE base_tables text[] := ARRAY[
  'accounts','accounting_periods','posting_events','vouchers','voucher_entries',
  'voucher_source_links','voucher_settlement_lines','voucher_attachment_links',
  'accounting_opening_lines','accounting_opening_cutover','posting_audit',
  'customer_receipts','receipt_allocations','customer_prepayments',
  'accounting_base_check_report'
];
BEGIN
  FOREACH role_name IN ARRAY ARRAY['invoice_app','invoice_test'] LOOP
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname=role_name) THEN
      IF role_name = 'invoice_app' THEN
        GRANT SELECT ON TABLE settings TO invoice_app;
      END IF;
      FOREACH table_name IN ARRAY base_tables LOOP
        IF role_name = 'invoice_app' THEN
          EXECUTE format('GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE %I TO %I',
                         table_name,role_name);
        ELSE
          EXECUTE format('GRANT ALL PRIVILEGES ON TABLE %I TO %I',table_name,role_name);
        END IF;
        sequence_name := pg_get_serial_sequence(table_name,'id');
        IF sequence_name IS NOT NULL THEN
          EXECUTE format('GRANT USAGE,SELECT ON SEQUENCE %s TO %I',sequence_name,role_name);
        END IF;
      END LOOP;
    END IF;
  END LOOP;
END $do$;
