-- 报价驱动工单结算：不可变报价修订与结算来源快照。
--
-- 兼容原则：
-- * 旧工单默认 contract_actual，不关联报价；
-- * 新报价工单在结算生成前跟随 quotations.current_revision_no；
-- * 结算创建时把修订号写入 customer_reimbursements，历史结算不重算；
-- * 本迁移只增加表/列，不改旧工单、旧结算和既有金额。

ALTER TABLE quotations
    ADD COLUMN IF NOT EXISTS current_revision_no bigint NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS quotation_revisions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quotation_id bigint NOT NULL REFERENCES quotations(id) ON DELETE CASCADE,
    revision_no bigint NOT NULL,
    snapshot_json text NOT NULL,
    subtotal numeric(14,2) NOT NULL DEFAULT 0,
    tax numeric(14,2) NOT NULL DEFAULT 0,
    total numeric(14,2) NOT NULL DEFAULT 0,
    created_by bigint NOT NULL REFERENCES users(id),
    created_at text NOT NULL,
    UNIQUE (quotation_id, revision_no)
);

ALTER TABLE quotation_revisions
    DROP CONSTRAINT IF EXISTS quotation_revisions_quotation_id_fkey;
ALTER TABLE quotation_revisions
    ADD CONSTRAINT quotation_revisions_quotation_id_fkey
    FOREIGN KEY (quotation_id) REFERENCES quotations(id) ON DELETE CASCADE;

CREATE INDEX IF NOT EXISTS idx_quotation_revisions_quote
    ON quotation_revisions(quotation_id, revision_no DESC);

ALTER TABLE service_orders
    ADD COLUMN IF NOT EXISTS settlement_basis text NOT NULL DEFAULT 'contract_actual';
DO $$ BEGIN
    ALTER TABLE service_orders
        ADD CONSTRAINT service_orders_settlement_basis_check
        CHECK (settlement_basis IN ('contract_actual','quotation')) NOT VALID;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

ALTER TABLE customer_reimbursements
    ADD COLUMN IF NOT EXISTS settlement_basis text NOT NULL DEFAULT 'contract_actual';
ALTER TABLE customer_reimbursements
    ADD COLUMN IF NOT EXISTS quotation_revision_id bigint REFERENCES quotation_revisions(id);

CREATE INDEX IF NOT EXISTS idx_customer_reimbursements_quote_revision
    ON customer_reimbursements(quotation_revision_id);

INSERT INTO settings(key,value)
VALUES ('postgresql_0299_quotation_pricing_revisions','complete')
ON CONFLICT (key) DO UPDATE SET value=excluded.value;
