BEGIN;

CREATE TABLE IF NOT EXISTS customer_prepayment_applications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prepayment_id bigint NOT NULL REFERENCES customer_prepayments(id),
    invoice_id bigint NOT NULL REFERENCES invoices(id),
    amount numeric(14,2) NOT NULL CHECK (amount > 0),
    currency text NOT NULL DEFAULT 'USD' CHECK (currency = 'USD'),
    occurrence_no integer NOT NULL CHECK (occurrence_no >= 1),
    status text NOT NULL DEFAULT 'active' CHECK (status IN ('active','reversed')),
    posting_event_id bigint REFERENCES posting_events(id),
    voucher_id bigint REFERENCES vouchers(id),
    created_by bigint REFERENCES users(id),
    created_at text NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    UNIQUE(prepayment_id,invoice_id,occurrence_no)
);
CREATE INDEX IF NOT EXISTS ix_prepayment_applications_invoice
    ON customer_prepayment_applications(invoice_id,status);

DO $do$
BEGIN
  IF current_database() = 'invoice_test'
     AND EXISTS (SELECT 1 FROM pg_roles WHERE rolname='invoice_test') THEN
    ALTER TABLE customer_prepayment_applications OWNER TO invoice_test;
  END IF;
END $do$;

DO $do$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='invoice_app') THEN
    GRANT SELECT,INSERT,UPDATE ON customer_prepayment_applications TO invoice_app;
    GRANT USAGE,SELECT ON SEQUENCE customer_prepayment_applications_id_seq TO invoice_app;
  END IF;
END $do$;

INSERT INTO settings(key,value)
VALUES ('postgresql_0301_customer_prepayment_applications','complete')
ON CONFLICT(key) DO UPDATE SET value=excluded.value;

COMMIT;
