BEGIN;

CREATE TABLE IF NOT EXISTS invoice_accounting_corrections (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id bigint NOT NULL REFERENCES invoices(id),
    correction_no integer NOT NULL CHECK (correction_no >= 1),
    accounting_date date NOT NULL,
    revenue_delta numeric(14,2) NOT NULL DEFAULT 0,
    sales_tax_delta numeric(14,2) NOT NULL DEFAULT 0,
    reason_code text NOT NULL CHECK (reason_code <> ''),
    status text NOT NULL DEFAULT 'posted' CHECK (status IN ('posted','reversed')),
    posting_event_id bigint REFERENCES posting_events(id),
    voucher_id bigint REFERENCES vouchers(id),
    created_by bigint REFERENCES users(id),
    created_at text NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    UNIQUE(invoice_id,correction_no),
    CHECK (revenue_delta <> 0 OR sales_tax_delta <> 0)
);
CREATE INDEX IF NOT EXISTS ix_invoice_accounting_corrections_invoice
    ON invoice_accounting_corrections(invoice_id,status);

DO $do$
BEGIN
  IF current_database() = 'invoice_test'
     AND EXISTS (SELECT 1 FROM pg_roles WHERE rolname='invoice_test') THEN
    ALTER TABLE invoice_accounting_corrections OWNER TO invoice_test;
  END IF;
END $do$;

DO $do$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='invoice_app') THEN
    GRANT SELECT,INSERT,UPDATE ON invoice_accounting_corrections TO invoice_app;
    GRANT USAGE,SELECT ON SEQUENCE invoice_accounting_corrections_id_seq TO invoice_app;
  END IF;
END $do$;

INSERT INTO settings(key,value)
VALUES ('postgresql_0303_invoice_accounting_corrections','complete')
ON CONFLICT(key) DO UPDATE SET value=excluded.value;

COMMIT;
