BEGIN;

-- 0306：工单结算「标记忽略」机制。
-- 已审核未计入的报销明细（includable）在提交/开票/发邮件/审核前会被硬拦截；
-- 允许用户将确属无需计入的明细显式标记忽略（带操作人、时间、原因），
-- 拦截校验将跳过被忽略的明细，同时保留审计留痕。外键语义与
-- customer_reimbursement_expense_links 保持一致：结算删除时忽略记录级联
-- 清理；报销明细外键 RESTRICT，防止被忽略引用时被静默删除。

CREATE TABLE public.customer_reimbursement_expense_ignores (
    id bigint NOT NULL,
    customer_reimbursement_id bigint NOT NULL,
    expense_item_id bigint NOT NULL,
    reason text DEFAULT ''::text NOT NULL,
    ignored_by bigint,
    ignored_at text NOT NULL
);

ALTER TABLE public.customer_reimbursement_expense_ignores
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.customer_reimbursement_expense_ignores_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    );

ALTER TABLE ONLY public.customer_reimbursement_expense_ignores
    ADD CONSTRAINT customer_reimbursement_expense_ignores_pkey PRIMARY KEY (id);

CREATE UNIQUE INDEX uq_customer_reimbursement_expense_ignores
    ON public.customer_reimbursement_expense_ignores USING btree (customer_reimbursement_id, expense_item_id);

CREATE INDEX idx_customer_reimbursement_expense_ignores_expense
    ON public.customer_reimbursement_expense_ignores USING btree (expense_item_id);

ALTER TABLE ONLY public.customer_reimbursement_expense_ignores
    ADD CONSTRAINT customer_reimbursement_expense_ignores_customer_reimbursement_id_fkey
    FOREIGN KEY (customer_reimbursement_id) REFERENCES public.customer_reimbursements(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.customer_reimbursement_expense_ignores
    ADD CONSTRAINT customer_reimbursement_expense_ignores_expense_item_id_fkey
    FOREIGN KEY (expense_item_id) REFERENCES public.expense_items(id) ON DELETE RESTRICT;

INSERT INTO settings(key,value)
VALUES ('postgresql_0306_customer_reimbursement_expense_ignores','complete')
ON CONFLICT(key) DO UPDATE SET value=excluded.value;

COMMIT;
