BEGIN;

-- 0308：统一商务单据（合同 / 报价单）模型与自驾交通计费、报价单折扣。
--
-- 目标（已确认业务规则）：
--   * 合同、报价单共用一个「商务单据」父模型 commercial_documents，通过
--     doc_type（contract / quotation）区分；工单用真实外键
--     service_orders.commercial_document_id 关联父表，不再用裸 ID 同时指向两张表。
--   * 合同、报价单共用统一费率明细结构 commercial_document_rates
--     （rate_type / unit / rate / billing_model），价格各自独立，取合集而非混合。
--     统一模型保留两个独立自驾项目：自驾里程单价（$/mile）与自驾交通工时单价（$/hr）。
--   * 每份商务单据独立配置「自驾交通计费方式」driving_billing_mode：
--     mileage_only / time_only / mileage_and_time。现有合同迁移为仅里程。
--   * 报价单增加折扣：gross_total（折扣前总额）/ discount_amount（默认 0）/
--     final_amount（最终报价金额 = 折扣前总额 - 折扣金额）。
--   * 报价单一对一工单：service_orders 上按 doc_type='quotation' 的
--     部分唯一索引，数据库层阻止同一报价单绑定第二个工单。
--
-- 兼容原则：
--   * 只新增表 / 列 / 索引，不改既有表与既有行金额；
--   * 已确认结算、已开票、已支付数据不受影响，不自动重新结算；
--   * 不改 C4 correction group、allocations、replacement SL、old superseded SL、
--     historical missing 组件、Tax Review、PB-2610-0001，也不改员工财务基线；
--   * 幂等：重复执行安全（IF NOT EXISTS / ON CONFLICT / EXCEPTION duplicate_object）。
--   * 明确不改：合同费率版本 contract_rate_versions/items —— 合同结算仍以
--     版本费率取价（历史追溯依据），commercial_document_rates 只镜像当前生效费率，
--     供统一结构展示与「从合同复制费率」。

-- ── 1) 商务单据父模型 ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS commercial_documents (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_type text NOT NULL CHECK (doc_type IN ('contract','quotation')),
    doc_ref_id bigint NOT NULL,
    client_id bigint,
    currency text NOT NULL DEFAULT 'USD',
    status text NOT NULL DEFAULT 'active',
    driving_billing_mode text NOT NULL DEFAULT 'mileage_only'
        CHECK (driving_billing_mode IN ('mileage_only','time_only','mileage_and_time')),
    settlement_mode text NOT NULL DEFAULT 'actual'
        CHECK (settlement_mode IN ('actual','fixed')),
    created_at text NOT NULL,
    updated_at text NOT NULL,
    UNIQUE (doc_type, doc_ref_id)
);

CREATE INDEX IF NOT EXISTS idx_commercial_documents_type
    ON commercial_documents(doc_type);
CREATE INDEX IF NOT EXISTS idx_commercial_documents_client
    ON commercial_documents(client_id);

-- ── 2) 统一费率明细结构（合同与报价单共用，价格各自独立）──────────────────
CREATE TABLE IF NOT EXISTS commercial_document_rates (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    commercial_document_id bigint NOT NULL
        REFERENCES commercial_documents(id) ON DELETE CASCADE,
    rate_type text NOT NULL,
    unit text NOT NULL,
    rate double precision NOT NULL DEFAULT 0,
    billing_model text NOT NULL DEFAULT 'rate',
    UNIQUE (commercial_document_id, rate_type)
);
CREATE INDEX IF NOT EXISTS idx_commercial_document_rates_doc
    ON commercial_document_rates(commercial_document_id);

-- ── 3) 工单统一绑定：真实外键 + 报价单一对一唯一索引 ──────────────────────
ALTER TABLE service_orders ADD COLUMN IF NOT EXISTS commercial_document_id bigint;
ALTER TABLE service_orders ADD COLUMN IF NOT EXISTS commercial_document_type text;

DO $$ BEGIN
    ALTER TABLE service_orders
        ADD CONSTRAINT service_orders_commercial_document_fkey
        FOREIGN KEY (commercial_document_id) REFERENCES commercial_documents(id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE service_orders
        ADD CONSTRAINT service_orders_commercial_document_type_check
        CHECK (commercial_document_type IN ('contract','quotation'));
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- 报价单一对一：同一报价单只能绑定一个工单（数据库层强制）。
CREATE UNIQUE INDEX IF NOT EXISTS ux_service_orders_one_quotation
    ON service_orders(commercial_document_id)
    WHERE commercial_document_id IS NOT NULL AND commercial_document_type = 'quotation';

-- ── 4) 报价单折扣与自驾/结算方式列 ─────────────────────────────────────────
ALTER TABLE quotations
    ADD COLUMN IF NOT EXISTS gross_total numeric(14,2) NOT NULL DEFAULT 0;
ALTER TABLE quotations
    ADD COLUMN IF NOT EXISTS discount_amount numeric(14,2) NOT NULL DEFAULT 0;
ALTER TABLE quotations
    ADD COLUMN IF NOT EXISTS final_amount numeric(14,2) NOT NULL DEFAULT 0;
ALTER TABLE quotations
    ADD COLUMN IF NOT EXISTS driving_billing_mode text NOT NULL DEFAULT 'mileage_only';
ALTER TABLE quotations
    ADD COLUMN IF NOT EXISTS settlement_mode text NOT NULL DEFAULT 'actual';

DO $$ BEGIN
    ALTER TABLE quotations
        ADD CONSTRAINT quotations_driving_billing_mode_check
        CHECK (driving_billing_mode IN ('mileage_only','time_only','mileage_and_time'));
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
    ALTER TABLE quotations
        ADD CONSTRAINT quotations_settlement_mode_check
        CHECK (settlement_mode IN ('actual','fixed'));
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
    ALTER TABLE quotations
        ADD CONSTRAINT quotations_discount_range_check
        CHECK (discount_amount >= 0 AND discount_amount <= gross_total);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ── 5) 合同自驾/结算方式列（新增列默认 mileage_only，即现有合同自动为仅里程）──
ALTER TABLE contracts
    ADD COLUMN IF NOT EXISTS driving_billing_mode text NOT NULL DEFAULT 'mileage_only';
ALTER TABLE contracts
    ADD COLUMN IF NOT EXISTS settlement_mode text NOT NULL DEFAULT 'actual';
DO $$ BEGIN
    ALTER TABLE contracts
        ADD CONSTRAINT contracts_driving_billing_mode_check
        CHECK (driving_billing_mode IN ('mileage_only','time_only','mileage_and_time'));
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
    ALTER TABLE contracts
        ADD CONSTRAINT contracts_settlement_mode_check
        CHECK (settlement_mode IN ('actual','fixed'));
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ── 5b) 工单结算折扣快照列：结算落库时记录「折扣前应收 gross_amount /
--         已应用折扣 discount_amount」，total_amount 始终为最终应收。
--         合同结算 discount_amount 保持 0，gross_amount = 明细合计，口径不变。──
ALTER TABLE customer_reimbursements
    ADD COLUMN IF NOT EXISTS gross_amount double precision NOT NULL DEFAULT 0;
ALTER TABLE customer_reimbursements
    ADD COLUMN IF NOT EXISTS discount_amount double precision NOT NULL DEFAULT 0;

-- 历史结算补列后保持对账自洽：gross_amount = 既有 total_amount（原应收未含折扣）
UPDATE customer_reimbursements
SET gross_amount = COALESCE(total_amount, 0)
WHERE gross_amount = 0 AND discount_amount = 0;

-- ── 6) 回填 ───────────────────────────────────────────────────────────────
-- 6a) 为既有合同建商务单据（driving_billing_mode 取新列默认 'mileage_only'）。
INSERT INTO commercial_documents
    (doc_type, doc_ref_id, client_id, currency, status, driving_billing_mode, settlement_mode, created_at, updated_at)
SELECT 'contract', c.id, c.client_id, COALESCE(c.currency,'USD'), 'active',
       COALESCE(c.driving_billing_mode,'mileage_only'), COALESCE(c.settlement_mode,'actual'),
       c.created_at, c.updated_at
FROM contracts c
ON CONFLICT (doc_type, doc_ref_id) DO NOTHING;

-- 6b) 为既有报价单建商务单据。
INSERT INTO commercial_documents
    (doc_type, doc_ref_id, client_id, currency, status, driving_billing_mode, settlement_mode, created_at, updated_at)
SELECT 'quotation', q.id, q.client_id, COALESCE(q.currency,'USD'), 'active',
       COALESCE(q.driving_billing_mode,'mileage_only'), COALESCE(q.settlement_mode,'actual'),
       q.created_at, q.updated_at
FROM quotations q
ON CONFLICT (doc_type, doc_ref_id) DO NOTHING;

-- 6c) 既有报价单折扣列回填：折扣前总额 = 既有 total（小计+税 / 固定总价），
--     折扣默认 0，最终报价金额 = 折扣前总额 - 折扣金额。仅回填未迁移过的行。
UPDATE quotations q
SET gross_total  = COALESCE(q.total, 0),
    discount_amount = 0,
    final_amount = COALESCE(q.total, 0)
WHERE q.gross_total = 0 AND q.discount_amount = 0 AND q.final_amount = 0;

-- 6d) 既有工单绑定商务单据：由 contract_id / quotation_id 回填。
UPDATE service_orders so
SET commercial_document_id = cd.id,
    commercial_document_type = cd.doc_type
FROM commercial_documents cd
WHERE so.commercial_document_id IS NULL
  AND ((cd.doc_type = 'contract' AND so.contract_id = cd.doc_ref_id)
       OR (cd.doc_type = 'quotation' AND so.quotation_id = cd.doc_ref_id));

-- 6e) 为既有合同镜像当前生效费率版本条目到统一费率表（合同结算仍走版本费率，
--     这里只作统一结构镜像与「从合同复制费率」来源）。取每份合同最新生效版本。
INSERT INTO commercial_document_rates
    (commercial_document_id, rate_type, unit, rate, billing_model)
SELECT cd.id, cri.rate_type, cri.unit, cri.rate, cri.billing_model
FROM commercial_documents cd
JOIN contract_rate_versions crv ON crv.status = 'active' AND crv.id = (
    SELECT crv2.id FROM contract_rate_versions crv2
    WHERE crv2.contract_id = cd.doc_ref_id AND crv2.status = 'active'
    ORDER BY crv2.effective_from DESC, crv2.version_no DESC, crv2.id DESC
    LIMIT 1
)
JOIN contract_rate_items cri ON cri.version_id = crv.id
WHERE cd.doc_type = 'contract'
ON CONFLICT (commercial_document_id, rate_type) DO NOTHING;

-- 迁移标记
INSERT INTO settings(key,value)
VALUES ('postgresql_0308_commercial_document_unified_rates','complete')
ON CONFLICT(key) DO UPDATE SET value=excluded.value;

COMMIT;
