/* Generate a reviewed-in-source supplement for UI literals missed by the
 * hand-maintained dictionaries. The input is produced by audit_ui_i18n.js.
 * Only repository UI copy is sent for translation; no application/user data.
 */
const fs = require("fs");
const path = require("path");
const https = require("https");

const root = path.resolve(__dirname, "..");
const input = path.resolve(process.env.AUDIT_JSON || path.join(root, ".i18n-audit.json"));
const output = path.join(root, "static", "ui-i18n-supplement.js");
const existingSupplement = fs.existsSync(output) ? require(output) : {};
const targets = { en: "en", nl: "nl", de: "de", es: "es" };
const findings = JSON.parse(fs.readFileSync(input, "utf8"));
const sources = [...new Set(findings.map(item => item.value))];
const han = /[\u3400-\u9fff]/;

function requestTranslation(text, language) {
  const url = new URL("https://translate.googleapis.com/translate_a/single");
  url.searchParams.set("client", "gtx");
  url.searchParams.set("sl", "zh-CN");
  url.searchParams.set("tl", language);
  url.searchParams.set("dt", "t");
  url.searchParams.set("q", text);
  return new Promise((resolve, reject) => {
    https.get(url, { headers: { "User-Agent": "invoice-tool-i18n-audit/1.0" } }, response => {
      let body = "";
      response.setEncoding("utf8");
      response.on("data", chunk => { body += chunk; });
      response.on("end", () => {
        if (response.statusCode !== 200) return reject(new Error(`HTTP ${response.statusCode}: ${body.slice(0, 200)}`));
        try {
          const payload = JSON.parse(body);
          resolve((payload[0] || []).map(part => part[0] || "").join(""));
        } catch (error) { reject(error); }
      });
    }).on("error", reject);
  });
}

async function pooledMap(values, concurrency, callback) {
  const result = new Array(values.length);
  let cursor = 0;
  async function worker() {
    while (cursor < values.length) {
      const index = cursor++;
      result[index] = await callback(values[index], index);
    }
  }
  await Promise.all(Array.from({ length: concurrency }, worker));
  return result;
}

const separator = "\nI18NSPLIT7F3A\n";
function batches(values, size) {
  const output = [];
  for (let index = 0; index < values.length; index += size) output.push(values.slice(index, index + size));
  return output;
}

async function translateBatch(batch, language) {
  const translated = await requestTranslation(batch.join(separator), language);
  const parts = translated.split(/\s*I18NSPLIT7F3A\s*/i).map(value => value.trim());
  if (parts.length === batch.length && parts.every(value => value && !han.test(value))) return parts;
  // The service occasionally changes a separator around punctuation. Fall
  // back only for that small batch, keeping the normal request count low.
  return pooledMap(batch, 4, source => requestTranslation(source, language));
}

(async () => {
  const supplement = {
    en: { ...(existingSupplement.en || {}) },
    nl: { ...(existingSupplement.nl || {}) },
    de: { ...(existingSupplement.de || {}) },
    es: { ...(existingSupplement.es || {}) },
  };
  for (const [name, language] of Object.entries(targets)) {
    process.stderr.write(`Translating ${sources.length} strings to ${name}...\n`);
    const sourceBatches = batches(sources, 24);
    const translatedBatches = await pooledMap(sourceBatches, 4, async (batch, index) => {
      for (let attempt = 1; attempt <= 4; attempt++) {
        try {
          const translated = await translateBatch(batch, language);
          if (translated.length === batch.length && translated.every(value => value && !han.test(value))) return translated;
          throw new Error("translation batch is incomplete or still contains Han characters");
        } catch (error) {
          if (attempt === 4) throw new Error(`${name} batch ${index + 1}: ${error.message}`);
          await new Promise(resolve => setTimeout(resolve, attempt * 500));
        }
      }
    });
    const values = translatedBatches.flat();
    sources.forEach((source, index) => { supplement[name][source] = values[index]; });
  }
  const body = `/* Generated by scripts/generate_ui_i18n_supplement.js. */\n` +
    `(function(root,factory){const value=factory();if(typeof module!=="undefined"&&module.exports)module.exports=value;else root.uiI18nSupplement=value;})(typeof globalThis!=="undefined"?globalThis:this,function(){return ${JSON.stringify(supplement, null, 2)};});\n`;
  fs.writeFileSync(output, body, "utf8");
  process.stderr.write(`Wrote ${output}\n`);
})().catch(error => { console.error(error); process.exitCode = 1; });
