"""Copy a verified SQLite snapshot into an EMPTY, explicitly named rehearsal DB.

No source mutations, no DROP/TRUNCATE, no disabled FK triggers. Import is one
transaction and all foreign keys validate before commit. Refuses production DBs.
"""
import argparse
import hashlib
import json
import os
from pathlib import Path
import sqlite3
import sys
import time

ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT))
from database import SCHEMA_VERSION
from scripts.pg_schema import schema_manifest,qi


def digest_rows(rows):
    encoded=sorted(json.dumps(list(r),ensure_ascii=True,separators=(',',':'),allow_nan=False) for r in rows)
    return hashlib.sha256(('\n'.join(encoded)).encode()).hexdigest()


def compare(source,target,manifest):
    result={}
    for table,meta in manifest.items():
        cols=','.join(qi(c['name']) for c in meta['columns'])
        left=source.execute('select '+cols+' from '+qi(table)).fetchall()
        right=target.execute('select '+cols+' from '+qi(table)).fetchall()
        if table=='audit_logs':
            # This is a polymorphic identifier, not an integer FK: AI manifests
            # use UUID text. Preserve every identifier, explicitly as text.
            pos=next(i for i,c in enumerate(meta['columns']) if c['name']=='entity_id')
            left=[tuple(str(v) if i==pos and v is not None else v for i,v in enumerate(row)) for row in left]
        a,b=digest_rows(left),digest_rows(right)
        if a!=b: raise ValueError('Row/value mismatch: '+table)
        result[table]={'rows':len(left),'sha256':a}
    return result


def migrate(source_path,url,target_name):
    if not target_name.endswith('_rehearsal'):
        raise ValueError('This tool is limited to *_rehearsal databases')
    return _migrate_snapshot(source_path,url,target_name)


def _migrate_snapshot(source_path,url,target_name,expected_sha=None,expected_user=None):
    """Shared transaction; public entrypoints must validate their own scope first."""
    import psycopg  # type: ignore[import-not-found]
    started=time.monotonic()
    source=sqlite3.connect(Path(source_path).resolve(strict=True).as_uri()+'?mode=ro',uri=True)
    source.execute('pragma query_only=on')
    source.execute('begin')
    try:
        if source.execute('pragma integrity_check').fetchone()[0]!='ok' or source.execute('pragma foreign_key_check').fetchall():
            raise ValueError('SQLite source integrity/foreign keys failed')
        manifest=schema_manifest(source)
        expected=json.loads((ROOT/'migrations/postgresql/schema-0252.json').read_text(encoding='utf-8-sig'))
        if manifest!=expected: raise ValueError('Source schema differs from reviewed 0252 baseline')
        sha=hashlib.sha256(Path(source_path).read_bytes()).hexdigest()
        if expected_sha is not None and sha!=expected_sha:
            raise ValueError('Frozen snapshot checksum changed')
        with psycopg.connect(url,connect_timeout=10,options='-c timezone=UTC') as target:
            if target.execute('select current_database()').fetchone()[0]!=target_name:
                raise ValueError('Target database identity mismatch')
            if expected_user is not None and target.execute('select current_user').fetchone()[0]!=expected_user:
                raise ValueError('Target migration role mismatch')
            if target.execute("select 1 from information_schema.tables where table_schema='public' limit 1").fetchone():
                raise ValueError('Target is not empty; refusing overwrite')
            target.execute((ROOT/'migrations/postgresql/0252-compat.sql').read_text())
            identities={}
            for table,meta in manifest.items():
                defs=[]
                primary=sorted((c for c in meta['columns'] if c['pk']),key=lambda c:c['pk'])
                for c in meta['columns']:
                    typ={'INTEGER':'bigint','REAL':'double precision','TEXT':'text'}[c['type'].upper()]
                    if table=='audit_logs' and c['name']=='entity_id': typ='text'
                    item=qi(c['name'])+' '+typ
                    identity=len(primary)==1 and c['pk'] and typ=='bigint'
                    if identity:
                        item+=' GENERATED BY DEFAULT AS IDENTITY'
                        identities[table]=c['name']
                    if c['notnull']: item+=' NOT NULL'
                    if c['dflt_value'] is not None and not identity: item+=' DEFAULT '+c['dflt_value']
                    defs.append(item)
                if primary: defs.append('PRIMARY KEY ('+','.join(qi(c['name']) for c in primary)+')')
                target.execute('CREATE TABLE '+qi(table)+' ('+','.join(defs)+')')
                for c in meta['columns']:
                    target.execute('insert into invoice_sqlite_columns values(%s,%s,%s,%s,%s,%s,%s)',
                        (table,c['cid'],c['name'],c['type'],c['notnull'],c['dflt_value'],c['pk']))
                cols=','.join(qi(c['name']) for c in meta['columns'])
                with target.cursor().copy('COPY '+qi(table)+' ('+cols+') FROM STDIN') as copy:
                    for row in source.execute('select '+cols+' from '+qi(table)):
                        copy.write_row(tuple(row))
            # Indexes precede FK creation because some referenced keys are UNIQUE.
            for table,meta in manifest.items():
                for i,index in enumerate(meta['indexes']):
                    if index['origin']=='pk': continue
                    if any(c['cid']<0 for c in index['columns']): raise ValueError('Unsupported expression index')
                    if index['sql']:
                        target.execute(index['sql'])
                    else:
                        name='uq_'+hashlib.sha256((table+str(i)).encode()).hexdigest()[:20]
                        target.execute('CREATE UNIQUE INDEX '+qi(name)+' ON '+qi(table)+' ('+','.join(qi(c['name']) for c in index['columns'])+')')
            fk_count=0
            for table,meta in manifest.items():
                for fk in meta['foreign_keys']:
                    if fk['seq']!=0: raise ValueError('Composite FK needs explicit migration')
                    target.execute('ALTER TABLE '+qi(table)+' ADD FOREIGN KEY ('+qi(fk['from'])+') REFERENCES '+qi(fk['table'])+' ('+qi(fk['to'])+') ON DELETE '+fk['on_delete']+' ON UPDATE '+fk['on_update'])
                    fk_count+=1
            for table,col in identities.items():
                maximum=source.execute('select max('+qi(col)+') from '+qi(table)).fetchone()[0] or 0
                previous=source.execute('select seq from sqlite_sequence where name=?',(table,)).fetchone()
                maximum=max(maximum,previous[0] if previous else 0)
                target.execute('select setval(pg_get_serial_sequence(%s,%s),%s,%s)',(table,col,max(1,maximum),maximum>0))
            tables=compare(source,target,manifest)
            target.execute('insert into invoice_schema_version(singleton,version,source_sha256) values(1,%s,%s)',(SCHEMA_VERSION,sha))
        return {'schema':SCHEMA_VERSION,'source_sha256':sha,'tables':tables,'table_count':len(tables),
                'rows':sum(t['rows'] for t in tables.values()),'validated_foreign_keys':fk_count,
                'sequences':len(identities),'seconds':round(time.monotonic()-started,3)}
    finally:
        source.close()


if __name__=='__main__':
    p=argparse.ArgumentParser(description=__doc__)
    p.add_argument('--source',required=True)
    p.add_argument('--target-name',required=True)
    p.add_argument('--result',required=True)
    args=p.parse_args()
    result=migrate(args.source,os.environ['DATABASE_URL'],args.target_name)
    Path(args.result).write_text(json.dumps(result,indent=2),encoding='utf-8')
    print(json.dumps({k:v for k,v in result.items() if k!='tables'}))
